// This test file was generated by AI.
import { test, expect } from '@playwright/test';

test.describe('Dog API response json', () => {
    test('should return expected data from api/dogs/random', async ({ request }) => {
        const response = await request.get('/api/dogs/random');

        // status code 200
        expect(response.status()).toBe(200);

        const body = await response.json(); 

        expect(body.success).toBe(true);
        expect(body.data).toBeTruthy();
        expect(body.data.imageUrl).toBeTruthy();
        expect(typeof body.data.imageUrl).toBe('string');
    });


    test('invalid route should return 404', async ({ request }) => {
        const response = await request.get('/api/dogs/invalid');
        expect(response.status()).toBe(404);

        const body = await response.json(); 

        expect(body.error).toBeTruthy();
        expect(body.error).toBe('Route not found');
    });


    test('image verification first load', async ({ page }) => {
        await page.goto('http://localhost:5173/');


        const image = page.getByRole('img', { name: 'Random dog' });
        await expect(image).toBeVisible();
        const src = await image.getAttribute('src');
        expect(src).toBeTruthy();
        expect(src).toMatch(/^https:\/\//);
    });



    test('image verification after button', async ({ page }) => {

        await page.goto('http://localhost:5173/');

        const responsePromise = page.waitForResponse('**/api/dogs/random');

        await page.getByRole('button', { name: 'Get Another Dog' }).click();


        await responsePromise;

        const image = page.getByRole('img', { name: 'Random dog' });
        await expect(image).toBeVisible();

        const src = await image.getAttribute('src');
        expect(src).toBeTruthy();
        expect(src).toMatch(/^https:\/\//);

    });

    test('shows error when api call fails', async ({ page }) => {
        await page.route('**/api/dogs/random', async (route) => {
            await route.abort();
        });

        await page.goto('http://localhost:5173/');

        const errorText = page.getByText(/error/i);
        await expect(errorText.first()).toBeVisible();
    });
});     